### ISSUE TITLE
What is c.Get("User")?

### ISSUE THREAD

**Issue by goodforever** [RayMan77/VcelinWebApp#1]
What is c.Get("User")? if I use curl as request client to update, How to write it about "User" and for c.BindJSON(&updateUserModel)  ?

func UpdateUser(c *gin.Context) {
	id := c.Params.ByName("id")
	user, err := c.Get("User")
	var updateUserModel UpdateUserModel

	if userID, ok := strconv.ParseUint(id, 10, 32); ok == nil {
		if err {
			err := c.BindJSON(&updateUserModel)

**Comment by ZemanOndrej** [comment]
This line gets user from context:
`user, err := c.Get("User")`
To get user I use JWT token where I store user id.
I decode the token and check if it is valid in `AuthRequired` middleware.
So if first you need to call login endpoint to get a token and then pass it with the update request.
Put the token to "token" header. Check `accountApi.go`.

**Comment by goodforever** [comment]
@ZemanOndrej Thanks!
